### ISSUE TITLE
[ DOCS ] : CREATE CODE_OF_CONDUCT 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [CodXCrypt/Whatsapp-API2#4]
## Follow These Basic Steps to Create Code of Conduct 

- Fork Repository 
- Go to Insights Section 
- Navigate to Community Section 
- Create Code of Conduct 
- Add `codxcryptcommunity@gmail.com` as method of contact 
- Push changes to new branch can name it `ADDED CODE OF CONDUCT` 
- Commit Changes 
- Create Pull Request And its Done 

### Request to Project Admin Please Assign this as Good First Issue

**Comment by unnati914** [comment]
Hi @rohan-kulkarni-25! Thanks for opening the issue :).

**Comment by rohan-kulkarni-25** [comment]
@unnati914  It will be great if some beginner will take this as they will get green square

**Comment by arsheelsheikh** [comment]
Can I work on this issue

**Comment by unnati914** [comment]
there you go :)

**Comment by arsheelsheikh** [comment]
should I add more content that code of conduct format has else 
should I just make a `code of conduct` file and add Gmail id

**Comment by arsheelsheikh** [comment]
I have added created and added `code of conduct`
